// 투자 현황 조회
GET http://localhost:5555/investment?limit=10&offset=2&sortBy=virtual&order=Highest

###

// 코멘트 리스트 조회
GET http://localhost:5555/corp:id?limit=5&offset=1&order=desc

###

// 코멘트 글 작성
POST http://localhost:5555/corp:id
Content-Type: application/json

{
  "name": "김연우",
  "amount": "1000000",
  "comment": "초기 투자",
  "password": "1234",
}

###

//코멘트 글 수정
PATCH http://localhost:5555/corp:id

{
  "comment": "코드잇 투자"
}

###

//코멘트 글 삭제
Delete http://localhost:5555/corp:id