// mockUser.js
const User = [
  {
    id: "user-0",
    name: "김연우",
    email: "alice@example.com",
    password: "1234",
    gender: "F",
    birth: new Date("1995-03-15"),
    created_at: new Date(),
    updated_at: new Date(),
    isDeleted: false,
  },
  {
    id: "user-1",
    name: "이유지",
    email: "bob@example.com",
    password: "1234",
    gender: "M",
    birth: new Date("1992-07-21"),
    created_at: new Date(),
    updated_at: new Date(),
    isDeleted: false,
  },
  {
    id: "user-2",
    name: "안다혜",
    email: "charlie@example.com",
    password: "1234",
    gender: "M",
    birth: new Date("1998-11-02"),
    created_at: new Date(),
    updated_at: new Date(),
    isDeleted: false,
  },
  {
    id: "user-3",
    name: "신희성",
    email: "diana@example.com",
    password: "1234",
    gender: "F",
    birth: new Date("2000-01-30"),
    created_at: new Date(),
    updated_at: new Date(),
    isDeleted: false,
  },
  {
    id: "user-4",
    name: "이용섭",
    email: "ethan@example.com",
    password: "1234",
    gender: "M",
    birth: new Date("1993-09-12"),
    created_at: new Date(),
    updated_at: new Date(),
    isDeleted: false,
  },
];

export default User;
