// 전체 조회
GET http://localhost:3000/corp


###
//조회 방식 6가지 가능(salesHighest, investmentHighest,
//                    employeeHighest, investmentLowest,
//                    salesLowest, employeeLowest)

GET http://localhost:3000/corp?limit=2&offset=0&order=investmentLowest
###

// 개별 조회
GET http://localhost:3000/corp/dae06a85-ab83-46b7-a3a7-8adfef1a6fd5



####
GET http://localhost:3000/corp?search=태크
